motion:
  att_wt: 10
  p_off_off: 0.7
  theta: 2.0
  p_off_min: 0.05
  p_off_max: 0.4
  d_min: 0.2
  d_max: 0.8
measurement:
  k: 30
  max_lvl: 0.5
  min_lvl: 0.2
  alpha: 1.0
  pca_dim: 4096
  p_off_prior: 0.2
  p_off_min: 0.1
  p_off_max: 0.5
